# Generated by Django 2.2.3 on 2019-07-12 08:27

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_setup_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=main.models.get_default_prefix, to='main.Prefix'),
        ),
    ]
