# Generated by Django 2.2.4 on 2019-09-19 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_setup_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temporarystorage',
            name='model_name',
        ),
    ]
