# Generated by Django 2.2.3 on 2019-07-11 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_setup_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='child_cu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_of', to='main.CompoundUnit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parent_cu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_of', to='main.CompoundUnit'),
        ),
    ]
