# Generated by Django 2.2.4 on 2019-08-15 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190815_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compoundunit',
            name='variables',
        ),
        migrations.AddField(
            model_name='variable',
            name='compoundunit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='variables', to='main.CompoundUnit'),
        ),
    ]
