# Generated by Django 2.2.3 on 2019-07-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190712_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='exponent',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='multiplier',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
