# Generated by Django 2.2.4 on 2019-09-23 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_temporarystorage_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='parent_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='encapsulated_components', to='main.CellModel'),
        ),
    ]
