# Generated by Django 2.2.4 on 2019-09-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190910_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='parent_component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_component', to='main.Component'),
        ),
    ]
