# Generated by Django 2.2.3 on 2019-07-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190716_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellmodel',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Everyone', 'EO'), ('Only me', 'ME'), ('Selected users', 'SU')], default='ME', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Everyone', 'EO'), ('Only me', 'ME'), ('Selected users', 'SU')], default='ME', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='compoundunit',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Everyone', 'EO'), ('Only me', 'ME'), ('Selected users', 'SU')], default='ME', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='encapsulation',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Everyone', 'EO'), ('Only me', 'ME'), ('Selected users', 'SU')], default='ME', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='math',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Everyone', 'EO'), ('Only me', 'ME'), ('Selected users', 'SU')], default='ME', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reset',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Everyone', 'EO'), ('Only me', 'ME'), ('Selected users', 'SU')], default='ME', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Everyone', 'EO'), ('Only me', 'ME'), ('Selected users', 'SU')], default='ME', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Everyone', 'EO'), ('Only me', 'ME'), ('Selected users', 'SU')], default='ME', max_length=3, null=True),
        ),
    ]
