# Generated by Django 2.2.4 on 2019-09-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190923_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='math',
            name='math_ml',
            field=models.TextField(blank=True, null=True),
        ),
    ]
