# Generated by Django 2.2.3 on 2019-07-16 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190716_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellmodel',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], default='Only me', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], default='Only me', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='compoundunit',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], default='Only me', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='encapsulation',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], default='Only me', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='math',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], default='Only me', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='reset',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], default='Only me', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], default='Only me', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='privacy',
            field=models.CharField(blank=True, choices=[('Public', 'Public'), ('Private', 'Private')], default='Only me', max_length=9, null=True),
        ),
    ]
