# Generated by Django 2.2.4 on 2019-09-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190918_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='models',
        ),
        migrations.AddField(
            model_name='component',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='components', to='main.CellModel'),
        ),
    ]
