# Generated by Django 2.2.4 on 2019-09-18 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_component_parent_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='all_components', to='main.CellModel'),
        ),
    ]
